import Head from "next/head";
import LeagueDisplay from ":)/components/v2/league-display";
import LeagueRules from ":)/components/v2/league-rules";
import { leagues } from ":)/utils/config";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dawgs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-full">
        <main className="container flex min-h-screen flex-col items-center justify-center overflow-hidden pb-24">
          <div className="flex w-full flex-col items-center justify-center gap-12 py-8">
            <div className="flex w-full flex-col justify-around gap-12 md:flex-row">
              {leagues.map((leagueId) => (
                <LeagueDisplay key={leagueId} leagueId={leagueId} />
              ))}
            </div>
          </div>
          <LeagueRules />
        </main>
      </div>
    </>
  );
}
