import Head from "next/head";
import LeagueDisplay from ":)/components/ui/LeagueDisplay";
import LeagueRules from ":)/components/v2/league-rules";
import ScoringSettingsDialog from ":)/components/v2/scoring-settings-dialog";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dawgs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-full">
        <main className="flex min-h-screen flex-col items-center justify-center overflow-hidden bg-slate-800 pb-24">
          <div className="container flex flex-col items-center justify-center gap-12 py-8">
            <ScoringSettingsDialog />
            <div className="flex w-full flex-col justify-around gap-12 md:flex-row">
              {/* <LeagueDisplay leagueId={"992980386516971520"} /> */}
              <LeagueDisplay leagueId={"1121980629639372800"} />
              <LeagueDisplay leagueId={"992986007853195264"} />
            </div>
          </div>
          <LeagueRules />
        </main>
      </div>
    </>
  );
}
